development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: askthem_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
        # Change whether the session persists in safe mode by default.
        # (default: false)
        safe: true

    scraped_local_gov:
      database: scraped_local_gov
      hosts:
        - localhost:27017
      options:
        safe: true
  # Configure Mongoid specific options. (optional)
  options:
    # Configuration for whether or not to allow access to fields that do
    # not have a field definition on the model. (default: true)
    # allow_dynamic_fields: true

    # Enable the identity map, needed for eager loading. (default: false)
    identity_map_enabled: true

    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serializaion. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Protect id and type from mass assignment. (default: true)
    # protect_sensitive_fields: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Skip the database version check, used when connecting to a db without
    # admin access. (default: false)
    # skip_version_check: false

    # User Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  sessions:
    default:
      database: askthem_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
    scraped_local_gov:
      database: scraped_local_gov_for_open_government_test
      hosts:
        - localhost:27017
      options:
        safe: true
<% default = URI.parse(ENV['MONGO_URL'] || 'mongodb://127.0.0.1:27017/askthem') %> # https://gist.github.com/2588954
<% scraped_local_gov = URI.parse(ENV['SCRAPED_LOCAL_GOV_URL'] || 'mongodb://127.0.0.1:27017/scraped_local_gov') %>
production:
  sessions:
    default:
      database: <%= default.path.sub '/', '' %>
<% if default.user %>
      username: <%= default.user %>
<% end %>
<% if default.password %>
      password: <%= default.password %>
<% end %>
      hosts:
      - <%= default.host %>:<%= default.port %>
      options:
        safe: true
    scraped_local_gov:
      database: <%= scraped_local_gov.path.sub '/', '' %>
<% if scraped_local_gov.user %>
      username: <%= scraped_local_gov.user %>
<% end %>
<% if scraped_local_gov.password %>
      password: <%= scraped_local_gov.password %>
<% end %>
      hosts:
        - <%= scraped_local_gov.host %>:<%= scraped_local_gov.port %>
      options:
        safe: true
  options:
    identity_map_enabled: true
